export default {
  ADD_ELEMENT       : 'ADD_ELEMENT',
  CANCEL            : 'CANCEL',
  DESTROY_ELEMENT   : 'DESTROY_ELEMENT',
  EDIT_ELEMENT      : 'EDIT_ELEMENT',
  EDIT_MODE_OFF     : 'EDIT_MODE_OFF',
  UPDATE_ELEMENT    : 'UPDATE_ELEMENT',
  SORT_ELEMENTS     : 'SORT_ELEMENTS'
};
